### ISSUE TITLE
Picture splicing is not perfect

### ISSUE THREAD

**Issue by Zvandaa** [s9roll7/face_crop_img2img#2]
i found some problem，when i using this extension
**Picture splicing is not perfect**

like this:

![微信图片_20230116180236](https://user-images.githubusercontent.com/122773384/212652225-84c77306-9454-482b-834d-1d95b29c01c1.png)

![微信图片_20230116180351](https://user-images.githubusercontent.com/122773384/212652154-d2f5406f-89a4-4830-895f-c4f97275fb0f.png)

![微信图片_20230116180540](https://user-images.githubusercontent.com/122773384/212652650-3c966c13-42f7-4adc-bf92-ba75a7b70d48.png)

please help~plz
how could i fix this?

**Comment by s9roll7** [comment]
Thanks for the report.
Compositing facial images is not always successful.
The success rate depends greatly on the composition of the original image and the values of [Denoising Strength][Face Denoising Strength].
You may succeed by reducing [Denoising Strength][Face Denoising Strength] or adjusting [Face Area Magnification].

**Comment by Zvandaa** [comment]
hi~我是周曦文~您的邮件我已经收到。

**Comment by Zvandaa** [comment]
OK，think you, i try to turn up [Face Area Magnification] ,i will work for me

![微信图片_20230117154047](https://user-images.githubusercontent.com/122773384/212837918-978b72ea-5d1e-44d0-ba3b-85e5b048060f.png)
